# Generated by Django 6.1 on 2026-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_team_project_teams'),
        ('sdlc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdlcphase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='sdlcphase',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='sdlcphase',
            constraint=models.UniqueConstraint(fields=('project', 'phase_name'), name='unique_phase_per_project'),
        ),
    ]
