# Generated by Django 6.1 on 2026-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_work_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_file',
            field=models.FileField(blank=True, null=True, upload_to='static/media/task_work/'),
        ),
    ]
